### PR TITLE
Show diff

### PR DESCRIPTION
**Pull request by Dinoshauer**
Quick addition for #5

### CODE REVIEW

**Comment by asottile** [comment]
I'll tell you what, I'm going to merge this and then merge mine on top of this (since I have a few tweaks and some unrelated fixes and an additional test).  But first I'm going to grab dinner :D

**Comment by Dinoshauer** [comment]
Bon apetit!

**Comment by asottile** [comment]
I'm going to rename the flag to `--diff-only` as well, because I think that is a little more indicative of its intent

**Comment by Dinoshauer** [comment]
:+1:

**Comment by asottile** [comment]
Thanks for the PR! :D

**Pull request merged**
